name: "Prepare Release"
description: "Bump version, update changelog, and create release PR"

inputs:
  version_part:
    description: "The part of the version to update (patch, minor or major)"
    required: true
    default: "minor"
  python_version:
    description: "Python version to use"
    required: true
    default: "3.10"
  python_package:
    description: "Python package name"
    required: true
    default: "kedro_vertexai"
  github_token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v4.7.1
      with:
        python-version: ${{ inputs.python_version }}

    - name: Validate inputs
      shell: bash
      run: |
        echo "INPUT_VERSION_PART: ${{ inputs.version_part }}"
        python -c "if '${{ inputs.version_part }}' not in ['patch', 'minor', 'major']: raise ValueError(\"'${{ inputs.version_part }}' must be one of ['patch', 'minor', 'major'])\")"

    - name: Bump the version number
      id: bump_version
      shell: bash
      env:
        PYTHON_PACKAGE: ${{ inputs.python_package }}
      run: |
        pip install bump2version
        bumpversion ${{ inputs.version_part }}
        echo "::set-output name=package_version::$(cat $PYTHON_PACKAGE/__init__.py | grep -Po  '\d+\.\d+\.\d+')"

    - name: Update the CHANGELOG according to 'Keep a Changelog' guidelines
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        version: ${{ steps.bump_version.outputs.package_version }}

    - name: Create a new release branch
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b release-${{ steps.bump_version.outputs.package_version }}
        git push -u origin release-${{ steps.bump_version.outputs.package_version }}

    - name: Open a PR to merge the release to master
      id: open_pr
      uses: vsoch/pull-request-action@1.1.1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PULL_REQUEST_BRANCH: master
        PULL_REQUEST_FROM_BRANCH: release-${{ steps.bump_version.outputs.package_version }}
        PULL_REQUEST_TITLE: "Release ${{ steps.bump_version.outputs.package_version }}"
        PULL_REQUEST_BODY: "Bump version and CHANGELOG for next release."

    - name: Commit the changes
      shell: bash
      run: |
        git commit -am "FIX #${{ steps.open_pr.outputs.pull_request_number }} - Bump version and CHANGELOG for release ${{ steps.bump_version.outputs.package_version }}"
        git push