name: End 2 End Test (Quickstart)

on:
  push:
    branches: 
      - master
      - develop
      - end-to-end-tests
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.8

    - name: Setup virtualenv
      run: |
        python -V
        python -m pip install virtualenv
        virtualenv venv
        source venv/bin/activate
   
    - name: Setup kedro spaceflights project
      run: |
        pip install . 'kedro<0.18' kedro-docker
        kedro new --starter spaceflights --config e2e/starter-config.yml
        

    - name: Install project dependencies
      run: |
        cd ./e2e/spaceflights
        cat src/requirements.txt
