name: End 2 End Test (Quickstart)

on:
  push:
    branches: 
      - master
      - develop
      - end-to-end-tests
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.8

    - name: Setup virtualenv
      run: |
        python -V
        python -m pip install virtualenv
        virtualenv venv
        source venv/bin/activate
   
    - name: Initialize kedro spaceflights project
      run: |
        pip install . 'kedro<0.18'
        mkdir -p ./e2e/spaceflights
        kedro new --starter spaceflights --config e2e/starter-config.yml --verbose

    - name: Install project dependencies
      run: |
        pwd
        cd ./spaceflights
        echo "git+https://github.com/getindata/kedro-vertexai.git@$GITHUB_SHA" >> src/requirements.txt
        echo "kedro-docker" >> src/requirements.txt
        sed -i '/kedro-telemetry/d' src/requirements.txt
        cat src/requirements.txt
        pip install -r src/requirements.txt

    - name: Init and update configuration
      run: |
        pwd
        cd ./spaceflights
        kedro docker init
        kedro vertexai init
        echo "!data/01_raw" >> .dockerignore
        mv ../catalog.yml conf/base/catalog.yml
        mv ../vertexai.yml conf/base/vertexai.yml

    - name: Prepare docker env
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Build pipeline docker image
      run: |
        pwd
        cd ./spaceflights
        docker build --tag kedro-vertexai-e2e:latest --load .

    - name: Publish docker image to GCR
      uses: mattes/gce-docker-push-action@v1
      with:
        creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        src: kedro-vertexai-e2e:latest
        dst: gcr.io/gid-ml-ops-sandbox/kedro-vertexai-e2e:${{ github.sha }}

    - name: Run project on vertex pipeline
      run: |
        pwd
        cd ./spaceflights
        export KEDRO_CONFIG_COMMIT_ID=$GITHUB_SHA
        kedro vertexai run-once

