name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version_part:
        description: The part of the version to update (patch, minor or major)
        required: true
        default: 'minor'

jobs:
  prepare-release:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4

      - name: Prepare release
        uses: ./.github/actions/prepare_release
        with:
          version_part: ${{ github.event.inputs.version_part }}
          python_version: ${{ matrix.python-version }}
          python_package: kedro_vertexai
          github_token: ${{ secrets.GITHUB_TOKEN }}
