name: "SonarCloud Scan"
description: "Run SonarCloud analysis on the project"

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  sonarcloud_token:
    description: "SonarCloud token for authentication"
    required: true
  project_base_dir:
    description: "Base directory for the project"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download coverage artifact
      uses: actions/download-artifact@v4
      with:
        name: coverage-3.10
        path: .

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5.3.1
      with:
        projectBaseDir: ${{ inputs.project_base_dir }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SONAR_TOKEN: ${{ inputs.sonarcloud_token }}